# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Covid-19' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire', '~> 5.5'
  pod 'Charts'

  # Pods for Covid-19

end
